import Navbar from '../components/navbar/Navbar'
import Footer from '@/components/footer/Footer'

import './globals.css'
import { Inter, Roboto, Poppins, } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'پروژه نکست جی اس',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa">
      <body className={inter.className}>
        
        <div className="container">

        <Navbar />

        {children}
        
        <Footer />
        
        </div>

      </body>

        
        
    </html>
  )
}
